### PR TITLE
Create TokenCard.md

### PR DESCRIPTION
**Pull request by Ahirice**
Adding TokenCard - the non-custodial Ethereum contract wallet

### CODE REVIEW

**Comment by sneg55** [comment]
> Adding TokenCard - the non-custodial Ethereum contract wallet

how TokenCard connected to DeFi?

**Comment by sneg55** [comment]
Also worth to mention that when I tried to create wallet it stuck on deploy contract wallet screen.

**Comment by Ahirice** [comment]
Sorry for your troubles with the app, would you mind trying again?

Regarding your first question, TokenCard is a fully non-custodial contract wallet, similar to Argent that is in that list. There are native integrations with DeFi services (Maker/Compound) coming soon too.

**Comment by sneg55** [comment]
> There are native integrations with DeFi services (Maker/Compound) coming soon too.

Can you follow up when it's ready?

**Comment by Ahirice** [comment]
I will for sure, but I'm not sure I understand why would a wallet like Argent make the cut (without having the integration yet) and not TokenCard.

**Comment by sneg55** [comment]
> I will for sure, but I'm not sure I understand why would a wallet like Argent make the cut (without having the integration yet) and not TokenCard.

They have Dex exchange feature built in, and also managed to get listed when there were a few products in Asset Management category and I was less picky on products.

**Pull request closed without merging**
